name: container-image

on:
  push:
    branches:
      - 'gh-action-secure'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image and push to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/osinfo:${{ github.sha }}
      - name: Pull image
        run: docker pull ${{ secrets.ACR_LOGIN_SERVER }}/osinfo:${{ github.sha }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: ${{ secrets.ACR_LOGIN_SERVER }}/osinfo:${{ github.sha }}
          format: json
          output: patch.json
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os
          severity: 'CRITICAL,HIGH'